name: GitHub PR Chore
on: push
  # pull_request:
  #   types:
  #     - closed

jobs:
  comment-on-merge:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      # - name: Set PR number
      #   run: echo "PR_NUMBER=${{ github.event.number }}" >> $GITHUB_ENV
      - name: Get Pull Request Number
        id: pr
        run: echo "PR_NUMBER=$(gh pr view --json number -q .number || echo "")" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Comment on the PR
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = process.env.PR_NUMBER;
            console.log(context.payload.number, "qwe", prNumber);
            github.rest.issues.createComment({
              issue_number: undefined,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "@coderabbitai assess this PR size with the following criteria and report it in your comment: \n- only include the relevant and main source files and changes in your assessment, for example changes in generated files like lock files should be excluded \n- the  assessment should be in the format of: ADDITIONS=number DELETIONS=number \n- no other text and explanation should be in your comment, just the number of addition and deletions that you have assessed \n- you assessment comment should also not include any of your tips or other sections"
            })
