name: GitHub PR Size Assessment Trigger
on:
  workflow_call:
    inputs:
      pr_number:
        required: true
        type: number
      repo:
        required: true
        type: string
      owner:
        required: true
        type: string
      merged:
        required: true
        type: boolean

jobs:
  assess-pr-size-on-merge:
    # if: inputs.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: rainlanguage/github-chore
          ref: 2025-06-30-update-readme
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Comment on the PR
        uses: actions/github-script@v7
        env:
          PR_NUMBER: ${{ inputs.pr_number }}
          REPO: ${{ inputs.repo }}
          OWNER: ${{ inputs.owner }}
        with:
          script: |
            const fs = require('fs');
            const body = fs.readFileSync('instructions.txt', 'utf8');
            github.rest.issues.createComment({
              body,
              repo: process.env.REPO,
              owner: process.env.OWNER,
              issue_number: parseInt(process.env.PR_NUMBER)
            })
